<?php

namespace ContainerTwPDREk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NJ6q1h0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nJ6q1h0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nJ6q1h0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cache' => ['privates', '.errored._UT8cm0', NULL, 'Cannot determine controller argument for "App\\Controller\\QuestionController::show()": the $cache argument is type-hinted with the non-existent class or interface: "App\\Controller\\CacheInterface". Did you forget to add a use statement?'],
            'markdownParser' => ['services', 'markdown.parser', 'getMarkdown_ParserService', false],
        ], [
            'cache' => '?',
            'markdownParser' => '?',
        ]);
    }
}
