<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9PaS9tH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9PaS9tH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9PaS9tH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9PaS9tH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9PaS9tH\App_KernelDevDebugContainer([
    'container.build_hash' => '9PaS9tH',
    'container.build_id' => '1e8f6104',
    'container.build_time' => 1705657432,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9PaS9tH');
